name: agent
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - arxiv==2.3.1
      - attrs==25.4.0
      - azure-ai-translation-text==1.0.1
      - azure-core==1.37.0
      - babeldoc==0.2.33
      - bitarray==3.8.0
      - bitstring==4.3.1
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - click-default-group==1.2.4
      - coloredlogs==15.0.1
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - deepl==1.27.0
      - deprecated==1.3.1
      - distro==1.9.0
      - docformatter==1.7.7
      - fastapi==0.128.0
      - feedparser==6.0.12
      - ffmpy==1.0.0
      - filelock==3.20.2
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gradio==5.35.0
      - gradio-client==1.10.4
      - gradio-pdf==0.0.22
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.2
      - isodate==0.7.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - levenshtein==0.27.3
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - networkx==3.6.1
      - numpy==2.2.6
      - ollama==0.6.1
      - onnx==1.20.0
      - onnxruntime==1.23.2
      - openai==2.14.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - pdf2zh==1.9.11
      - pdfminer-six==20250416
      - peewee==3.18.3
      - pikepdf==10.1.0
      - pillow==11.3.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.1
      - pyclipper==1.4.0
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pymupdf==1.25.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-levenshtein==0.27.3
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - rapidocr-onnxruntime==1.4.4
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - ruff==0.14.10
      - safehttpx==0.1.7
      - scikit-image==0.26.0
      - scipy==1.16.3
      - semantic-version==2.10.0
      - sgmllib3k==1.0.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - socksio==1.0.0
      - starlette==0.50.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - tencentcloud-sdk-python-common==3.1.26
      - tencentcloud-sdk-python-tmt==3.0.1478
      - tifffile==2025.12.20
      - tiktoken==0.12.0
      - toml==0.10.2
      - tomlkit==0.13.3
      - toposort==1.10
      - tqdm==4.67.1
      - typer==0.21.0
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - untokenize==0.1.1
      - urllib3==2.6.2
      - uv==0.9.21
      - uvicorn==0.40.0
      - websockets==15.0.1
      - wrapt==2.0.1
      - xinference-client==1.16.0
      - xsdata==25.7
      - yarl==1.22.0